services:
  # 🤖 1. The Python/Flask Backend
  - type: web
    name: roast-master-backend
    runtime: python
    plan: free
    rootDir: roast-master-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  # 🌐 2. The Static Web Frontend
  - type: web # 👈 Changed this from static to web
    name: roast-master-frontend
    runtime: static # 👈 Added this line to let Render know it's a static site
    plan: free
    rootDir: roast-master-frontend
    buildCommand: "" 
    publishDir: "."
